name = "MyProject"
uuid = "79579629-c181-4b1f-abc6-12069b02827e"
authors = ["U_F_O"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
